### ISSUE TITLE
Remove dependencies

### ISSUE THREAD

**Issue by dy** [chrisguttandin/audio-context-timers#199]
Hi @chrisguttandin!
This seems to be a great package for audio purposes.
Would you consider removing heavy dependencies from the package runtime, like `@babel/runtime` and `tslib`? Are they unavoidable?

**Comment by chrisguttandin** [comment]
Thanks @dy.

My reasoning for using these packages was to reduce the bundle size.

The code is written in TypeScript and therefore needs to be translated by the TypeScript compiler. TypeScript uses some helper functions in the JavaScript code it produces. By default these helper functions get copy/pasted whenever they are needed which can result in duplicate code. `tslib` contains all those functions so it can be used as a replacement for the hard coded helper functions and potentially reduces the bundle size.

I additionally use Babel to produce the ES5 version of this package. `@babel/runtime` works in similar way.

I just made a quick test with Rollup. It's tree-shaking algorithm can completely eliminate `tslib` despite of the four used functions `_slicedToArray()`, `_arrayWithHoles()`, `_iterableToArrayLimit()`, `_nonIterableRest()`.

I hope this all makes sense.

**Comment by chrisguttandin** [comment]
Hi @dy, did my answer dispel your doubts on using the utility packages? Or in other words, can I close this issue?

I surely don't know everything about bundling and there might be some aspect that I'm missing. Please let me know if there is something I haven't considered.

**Comment by dy** [comment]
Yes, @chrisguttandin, thanks for the reply. That’s reasonable.
