### ISSUE TITLE
What is the difference between Worker Timers and Audio Context Timers?

### ISSUE THREAD

**Issue by KVPasupuleti** [chrisguttandin/audio-context-timers#455]
Both the packages serve the same purpose. But, why two?

Is there any advantage of using one over the other?

@chrisguttandin 

Please let me know.

**Comment by chrisguttandin** [comment]
Hi @KVPasupuleti,

I initially created worker-timers to keep a timer (setTimeout/setInterval) running on pages which are not visible. At some point Chrome changed the behavior and also throttled workers. I therefore came up with this package which apparently worked at that time.

Some time later the changes in Chrome got reverted and worker-timers worked again. Afterwards autoplay mechanisms were added to almost all browsers which means that this package doesn't work anymore unless the AudioContext is allowed to start.

Both packages use undocumented implementation specific browser behavior. Sometimes they work, sometimes they don't. :-(
